language: objective-c
before_install:
    - brew update
    - brew install xctool
before_script:
  - bundle install
  - cd Project && pod install && cd $TRAVIS_BUILD_DIR
  - git submodule init
  - git submodule update
  - cd Project/OctoCrash/OctoCrash/External/OctoKit && script/bootstrap && cd $TRAVIS_BUILD_DIR
script: make test