language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - bundle install
  - cd Project && pod install && cd $TRAVIS_BUILD_DIR
  - git submodule init
  - git submodule update
  - cd Project/OctoCrash/OctoCrash/External/OctoKit && script/bootstrap && cd $TRAVIS_BUILD_DIR
script: make test