platform :ios, "6.0"
workspace "OctoCrash.xcworkspace"

xcodeproj "OctoCrash/OctoCrash.xcodeproj"
link_with "OctoCrash", "OctoCrashTests"

target "OctoCrashTests", :exclusive => true do
  pod 'Kiwi', '~> 2.2.3'
end

target "OctoCrash", :exclusive => true do
  pod "AFNetworking", "~> 2.0"
end