platform :ios, "6.0"
workspace "OctoCrash.xcworkspace"

xcodeproj "OctoCrash/OctoCrash.xcodeproj"
link_with "OctoCrash", "OctoCrashTests"

target "OctoCrashTests", :exclusive => true do
  pod 'Kiwi/XCTest'
end	